package fit.iuh.dulichgiare.entity;
// Generated Mar 13, 2023, 11:14:32 AM by Hibernate Tools 4.3.6.Final

import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Policy generated by hbm2java
 */
@Entity
@Table(name = "policy")
public class Policy implements java.io.Serializable {

    private long id;
    private String policyName;
    private String priceincludes;
    private String pricenotincluded;
    private String childfare;
    private String paymentconditions;
    private String conditionregistering;
    private String notecancel;
    private String contact;
    private Set<Tour> tours;

    public Policy() {
    }

    public Policy(long id, String policyName, String priceincludes, String pricenotincluded, String childfare,
            String paymentconditions, String conditionregistering, String notecancel, String contact) {
        this.id = id;
        this.policyName = policyName;
        this.priceincludes = priceincludes;
        this.pricenotincluded = pricenotincluded;
        this.childfare = childfare;
        this.paymentconditions = paymentconditions;
        this.conditionregistering = conditionregistering;
        this.notecancel = notecancel;
        this.contact = contact;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "priceincludes", nullable = false)
    public String getPriceincludes() {
        return this.priceincludes;
    }

    public void setPriceincludes(String priceincludes) {
        this.priceincludes = priceincludes;
    }

    @Column(name = "pricenotincluded", nullable = false)
    public String getPricenotincluded() {
        return this.pricenotincluded;
    }

    public void setPricenotincluded(String pricenotincluded) {
        this.pricenotincluded = pricenotincluded;
    }

    @Column(name = "childfare", nullable = false)
    public String getChildfare() {
        return this.childfare;
    }

    public void setChildfare(String childfare) {
        this.childfare = childfare;
    }

    @Column(name = "paymentconditions", nullable = false)
    public String getPaymentconditions() {
        return this.paymentconditions;
    }

    public void setPaymentconditions(String paymentconditions) {
        this.paymentconditions = paymentconditions;
    }

    @Column(name = "conditionregistering", nullable = false)
    public String getConditionregistering() {
        return this.conditionregistering;
    }

    public void setConditionregistering(String conditionregistering) {
        this.conditionregistering = conditionregistering;
    }

    @Column(name = "notecancel", nullable = false)
    public String getNotecancel() {
        return this.notecancel;
    }

    public void setNotecancel(String notecancel) {
        this.notecancel = notecancel;
    }

    @Column(name = "contact", nullable = false)
    public String getContact() {
        return this.contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    @Column(name = "policyname", nullable = false)
    public String getPolicyName() {
        return this.policyName;
    }

    public void setPolicyName(String policyName) {
        this.policyName = policyName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "policy")
    public Set<Tour> getTours() {
        return this.tours;
    }

    public void setTours(Set<Tour> tours) {
        this.tours = tours;
    }

}
