package fit.iuh.dulichgiare.entity;

import java.time.LocalDate;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Promotion generated by hbm2java
 */
@Entity
@Table(name = "promotion")
public class Promotion implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -4417862474453757891L;
    private long id;
    private boolean active;
    private Set<Tour> tours;
    private String name;
    private double discount;
    private LocalDate endday;

    public Promotion() {
    }

    public Promotion(long id, String name, double discount, LocalDate endday) {
        super();
        this.id = id;
        this.name = name;
        this.discount = discount;
        this.endday = endday;
    }

    public Promotion(String name, double discount, LocalDate endday) {
        super();
        this.name = name;
        this.discount = discount;
        this.endday = endday;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "promotion")
    public Set<Tour> getTours() {
        return this.tours;
    }

    public void setTours(Set<Tour> tours) {
        this.tours = tours;
    }

    @Column(name = "name", nullable = true)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "discount", nullable = true, precision = 17, scale = 17)
    public double getDiscount() {
        return this.discount;
    }

    public void setDiscount(double discount) {
        this.discount = discount;
    }

//    @Temporal(TemporalType.LocalDate)
    @Column(name = "endday", nullable = true, length = 13)
    public LocalDate getEndday() {
        return this.endday;
    }

    public void setEndday(LocalDate endday) {
        this.endday = endday;
    }

    @Column(name = "active", nullable = false)
    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

}
