package fit.iuh.dulichgiare.entity;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.NoArgsConstructor;

/**
 * Tour generated by hbm2java
 */
@Entity
@Table(name = "tour")

@NoArgsConstructor
public class Tour implements java.io.Serializable {
    private long id;
    private boolean active;
    private String name;
    private String image;
    private String departure;
    private String departureTime;
    private String destination;
    private LocalDate startday;
    private LocalDate endday;
    private int numberofday;
    private int numberofpeople;
    private int subcriber;
    private String type;
    private double price;
    private LocalDateTime createat;
    private int liked;
    private String createdBy;
    private Set<Booking> orders;
    private Set<TourGuideTour> tourguideTours;
    private Set<Itinerary> itineraries;
    private Promotion promotion;
    private Set<TourDetail> tourdetails;
    private Policy policy;

    /**
     * @param active
     * @param name
     * @param image
     * @param departure
     * @param destination
     * @param startday
     * @param endday
     * @param numberofday
     * @param numberofpeople
     * @param subcriber
     * @param type
     * @param price
     * @param createat
     * @param liked
     * @param createdBy
     * @param promotion
     * @param policy
     */
    public Tour(boolean active, String name, String image, String departureTime, String departure, String destination,
            LocalDate startday, LocalDate endday, int numberofday, int numberofpeople, int subcriber, String type,
            double price, LocalDateTime createat, int liked, String createdBy, Promotion promotion, Policy policy) {
        super();
        this.active = active;
        this.name = name;
        this.image = image;
        this.departureTime = departureTime;
        this.departure = departure;
        this.destination = destination;
        this.startday = startday;
        this.endday = endday;
        this.numberofday = numberofday;
        this.numberofpeople = numberofpeople;
        this.subcriber = subcriber;
        this.type = type;
        this.price = price;
        this.createat = createat;
        this.liked = liked;
        this.createdBy = createdBy;
        this.promotion = promotion;
        this.policy = policy;
    }

    /**
     * @param active
     * @param name
     * @param image
     * @param departure
     * @param destination
     * @param startday
     * @param endday
     * @param numberofday
     * @param numberofpeople
     * @param subcriber
     * @param type
     * @param price
     * @param createat
     * @param liked
     * @param createdBy
     * @param policy
     */
    public Tour(boolean active, String name, String image, String departureTime, String departure, String destination,
            LocalDate startday, LocalDate endday, int numberofday, int numberofpeople, int subcriber, String type,
            double price, LocalDateTime createat, int liked, String createdBy, Policy policy) {
        super();
        this.active = active;
        this.name = name;
        this.image = image;
        this.departureTime = departureTime;
        this.departure = departure;
        this.destination = destination;
        this.startday = startday;
        this.endday = endday;
        this.numberofday = numberofday;
        this.numberofpeople = numberofpeople;
        this.subcriber = subcriber;
        this.type = type;
        this.price = price;
        this.createat = createat;
        this.liked = liked;
        this.createdBy = createdBy;
        this.policy = policy;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "active", nullable = false)
    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    @Column(name = "name", nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "image", nullable = false)
    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    @Column(name = "departure", nullable = false)
    public String getDeparture() {
        return this.departure;
    }

    public void setDeparture(String departure) {
        this.departure = departure;
    }

    @Column(name = "destination", nullable = false)
    public String getDestination() {
        return this.destination;
    }

    public void setDestination(String destination) {
        this.destination = destination;
    }

//    @Temporal(TemporalType.LocalDate)
    @Column(name = "startday", nullable = false, length = 13)
    public LocalDate getStartday() {
        return this.startday;
    }

    public void setStartday(LocalDate startday) {
        this.startday = startday;
    }

    @Column(name = "endday", nullable = false, length = 13)
    public LocalDate getEndday() {
        return this.endday;
    }

    public void setEndday(LocalDate endday) {
        this.endday = endday;
    }

    @Column(name = "numberofday", nullable = false)
    public int getNumberofday() {
        return this.numberofday;
    }

    public void setNumberofday(int numberofday) {
        this.numberofday = numberofday;
    }

    @Column(name = "numberofpeople", nullable = false)
    public int getNumberofpeople() {
        return this.numberofpeople;
    }

    public void setNumberofpeople(int numberofpeople) {
        this.numberofpeople = numberofpeople;
    }

    @Column(name = "subcriber", nullable = false)
    public int getSubcriber() {
        return this.subcriber;
    }

    public void setSubcriber(int subcriber) {
        this.subcriber = subcriber;
    }

    @Column(name = "type", nullable = false, length = 45)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "price", nullable = false, precision = 17, scale = 17)
    public double getPrice() {
        return this.price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    @Column(name = "createat", nullable = false,columnDefinition = "TIMESTAMP")
    public LocalDateTime getCreateat() {
        return this.createat;
    }

    public void setCreateat(LocalDateTime createat) {
        this.createat = createat;
    }

    @Column(name = "liked", nullable = false)
    public int getLiked() {
        return this.liked;
    }

    public void setLiked(int liked) {
        this.liked = liked;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tour")
    public Set<Booking> getOrders() {
        return this.orders;
    }

    public void setOrders(Set<Booking> orders) {
        this.orders = orders;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tour")
    public Set<TourGuideTour> getTourguideTours() {
        return this.tourguideTours;
    }

    public void setTourguideTours(Set<TourGuideTour> tourguideTours) {
        this.tourguideTours = tourguideTours;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tour")
    public Set<Itinerary> getItineraries() {
        return this.itineraries;
    }

    public void setItineraries(Set<Itinerary> itineraries) {
        this.itineraries = itineraries;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tour")
    public Set<TourDetail> getTourdetails() {
        return tourdetails;
    }

    public void setTourdetails(Set<TourDetail> tourdetails) {
        this.tourdetails = tourdetails;
    }

    @Column(name = "createdby", nullable = false)
    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "policy_id", nullable = false)
    public Policy getPolicy() {
        return this.policy;
    }

    public void setPolicy(Policy policy) {
        this.policy = policy;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "promotion_id", nullable = true)
    public Promotion getPromotion() {
        return this.promotion;
    }

    public void setPromotion(Promotion promotion) {
        this.promotion = promotion;
    }

    @Column(name = "departuretime", nullable = false)
    public String getDepartureTime() {
        return departureTime;
    }

    public void setDepartureTime(String departureTime) {
        this.departureTime = departureTime;
    }

}
