package fit.iuh.dulichgiare.entity;
// Generated Mar 13, 2023, 11:14:32 AM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * TourguideTour generated by hbm2java
 */
@Entity
@Table(name = "tourguide_tour")
public class TourGuideTour implements java.io.Serializable {

    private long id;
    private Tour tour;
    private TourGuide tourguide;

    public TourGuideTour() {
    }

    public TourGuideTour(long id, Tour tour, TourGuide tourguide) {
        this.id = id;
        this.tour = tour;
        this.tourguide = tourguide;
    }

    /**
     * @param tour
     * @param tourguide
     */
    public TourGuideTour(Tour tour, TourGuide tourguide) {
        super();
        this.tour = tour;
        this.tourguide = tourguide;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tour_id", nullable = false)
    public Tour getTour() {
        return this.tour;
    }

    public void setTour(Tour tour) {
        this.tour = tour;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tourguide_id", nullable = false)
    public TourGuide getTourguide() {
        return this.tourguide;
    }

    public void setTourguide(TourGuide tourguide) {
        this.tourguide = tourguide;
    }

}
