package fit.iuh.dulichgiare.entity;
// Generated Mar 13, 2023, 11:14:32 AM by Hibernate Tools 4.3.6.Final

import java.time.LocalDate;
import java.util.List;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;

/**
 * UserRequestTravel generated by hbm2java
 */
@Entity
@Table(name = "user_request_travel")
@AllArgsConstructor
public class UserRequestTravel implements java.io.Serializable {

    private long id;
    private List<Object> itineraryTravels;
    private boolean active;
    private String departure;
    private String destination;
    private double price;
    private int numberofpeople;
    private String type;
    private LocalDate startDate;
    private LocalDate endDate;
    private LocalDate createAt;
    private LocalDate updateAt;
    private String status;
    private Customer customer;

    public UserRequestTravel() {
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "departure", nullable = false)
    public String getDeparture() {
        return this.departure;
    }

    public void setDeparture(String departure) {
        this.departure = departure;
    }

    @Column(name = "destination", nullable = false)
    public String getDestination() {
        return this.destination;
    }

    public void setDestination(String destination) {
        this.destination = destination;
    }

    @Column(name = "price", nullable = false, precision = 17, scale = 17)
    public double getPrice() {
        return this.price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    @Column(name = "numofpeople", nullable = false)
    public int getNumberofpeople() {
        return this.numberofpeople;
    }

    public void setNumberofpeople(int numofpeople) {
        this.numberofpeople = numofpeople;
    }

    @Column(name = "type", nullable = false, length = 45)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "customer_id", nullable = false)
    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    @Column(name = "startdate", nullable = false, length = 45)
    public LocalDate getStartDate() {
        return startDate;
    }

    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    @Column(name = "enddate", nullable = false, length = 45)
    public LocalDate getEndDate() {
        return endDate;
    }

    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    @Column(name = "createat", nullable = false, length = 13)
    public LocalDate getCreateAt() {
        return createAt;
    }

    public void setCreateAt(LocalDate createAt) {
        this.createAt = createAt;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "updateat", nullable = true, length = 13)
    public LocalDate getUpdateAt() {
        return updateAt;
    }

    public void setUpdateAt(LocalDate updateAt) {
        this.updateAt = updateAt;
    }

    @Column(name = "active", nullable = false)
    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    @Column(name = "itinerarys", nullable = true)
    public List<Object> getItineraryTravels() {
        return itineraryTravels;
    }

    public void setItineraryTravels(List<Object> itineraryTravels) {
        this.itineraryTravels = itineraryTravels;
    }

}
